### ISSUE TITLE
[BUG] PR #1805 - "Danger" code review step has NodeJS crashing

### ISSUE THREAD

**Issue by guilhermeblanco** [twilio-labs/open-pixel-art#1806]
In case the build output gets lost:

```
11: 0xecda4a v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/opt/hostedtoolcache/node/10.17.0/x64/bin/node]

12: 0xecdfd7 v8::internal::Factory::NewFixedArrayWithHoles(int, v8::internal::PretenureFlag) [/opt/hostedtoolcache/node/10.17.0/x64/bin/node]

13: 0xb98630  [/opt/hostedtoolcache/node/10.17.0/x64/bin/node]

14: 0xb98f67 v8::internal::Builtin_ArrayConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/opt/hostedtoolcache/node/10.17.0/x64/bin/node]

15: 0x21bb55fdbf7d 

Error:  Error: Got no results back from the Dangerfile evaluation, this is likely an issue with a custom sub-process exiting early.
    at Executor.<anonymous> (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:140:35)
    at step (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:32:23)
    at Object.next (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:13:53)
    at /home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:3:12)
    at Executor.handleResults (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/runner/Executor.js:134:16)
    at Object.<anonymous> (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:162:47)
    at step (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:43:23)
    at Object.next (/home/runner/work/open-pixel-art/open-pixel-art/node_modules/danger/distribution/commands/utils/runDangerSubprocess.js:24:53)
##[error]Process completed with exit code 1.
```

**Comment by dkundel** [comment]
Hi @guilhermeblanco this seems to be an intermittent issue with GitHub Actions atm :( I hope this will be fixed by the time Actions goes GA. Thanks for flagging it!

**Comment by jerith** [comment]
It looks like this is still happening. 😿

**Comment by dkundel** [comment]
Seems like this is an issue inside of Danger that is currently being investigated

https://github.com/danger/danger-js/issues/985

**Comment by dkundel** [comment]
I'm creating a PR for Danger JS that will change the internal implementation of the JSON patch algorithm. If that PR gets merged we need to bump the Danger version and fix the `Dangerfile` to be compatible with the new version.

Otherwise, based on the implementation in [`rfc6902`](https://www.npmjs.com/package/rfc6902) we need to change from an array of pixels to an object. This would significantly improve the performance and remove the memory issue.
