### ISSUE TITLE
[BUG] "npm test" fails

### ISSUE THREAD

**Issue by cpbarton1** [twilio-labs/open-pixel-art#2723]
## Description
Running npm test on an unmodified pull produces the following output:

        const importedConfig = await import(configUrl.href);
                                     ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\7chri\Documents\Code\Projects\Twilio\open_source\open-pixel-art\node_modules\jest-config\build\index.js:99:3)
npm ERR! Test failed.  See above for more details.

I am running npm 6.14.8 on Windows 10

## Expected Behavior
The unmodified repository should pass its own tests

**Comment by Gatodillo** [comment]
With Windows 10, npm v6.14.8 and a recent clone of the repo (master branch) I can't reproduce this issue. @cpbarton1  are you still experimenting this bug?

**Comment by cpbarton1** [comment]
@Gatodillo No more.  Turns out node was out of date.  Environment issue only.  My mistake.
